CollegeERP/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('info.urls')),
    path('info/', include('info.urls')),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='info/login.html'), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(template_name='info/logout.html'), name='logout'),
    
    path('home/', include('Home.urls')),

]

Home/urls.py
from django.urls import path,include
from . import views
app_name='Home'
urlpatterns = [
path('',views.home_page,name='home'),
path('about/',views.about,name='about'),
path('contact/',views.contact,name='contact'),
path('calendar/',views.calendar,name='calendar'),
# path('camtest/',views.camtest,name='camtest')
]

Home/models.py
from django.db import models

# Create your models here.

Home/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def home_page(request):
     # return HttpResponse('hi')
     return render(request,'Home/mainhomepage.html')

def about(request):
     return render(request,'Home/aboutUs.html')

def contact(request):
     return render(request,'Home/contact.html')

def calendar(request):
     return render(request,'Home/calendar.html')

# def camtest(request):
#      import cv2
#      camera = cv2.VideoCapture(0)
#      return_value, image = camera.read()
#      cv2.imwrite('img.png', image)
#      del(camera)

Home/templates/Home/aboutUs.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name = "viewport" content = "width=device-width,initial-scale=1.0">
        <title>About Us</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'Home/css/styleAbout.css' %}">
    </head>
    <body>
        <header>
            <a id="logo" href="{% url 'Home:home' %}">
                <img src="{% static 'Home/images/amrita.jpg' %}" alt="Logo">
                <span>Smart Attendance Management System</span>
            </a>

            <!-- Main Navigation Links-->
            <nav>
                <ul>
                    <li><a href="{% url 'Home:home'%}">Home</a></li>
                    <li><a href="{% url 'Home:about'%}">About</a></li>
                    <li><a href="{% url 'Home:contact'%}">Contact Us</a></li>
                    <li><a href="{% url 'Home:calendar' %}">Calendar</a></li>

                    <li><a href="{% url 'login'%}">Login</a></li>
                </ul>
            </nav>

        </header>
        <div class="container">
            <h1>Smart Attendance Management System</h1>
            <h2> ~ Based on Facial Recognition</h2>
            <div class="image">
                <img src="{% static 'Home/images/Attendance.jpg' %}" alt="Attendance">
            </div>
            <p>
                To maintain the attendance record with day to day activities is a challenging task. 
                The conventional method of calling name of each student is time consuming and there is always a chance of proxy attendance. 
                The following system is based on face recognition to maintain the attendance record of students. 
                The daily attendance of students is recorded subject wise which is stored already by the administrator. As the time for corresponding subject arrives the system automatically starts taking snaps and then apply face detection and recognition technique to the given image and the recognize students are marked as present and their attendance update with corresponding time and subject id. 
            </p>
            <a href="{% url 'Home:home'%}" class="btn"> Back </a>
        </div>
    </body>
</html>

Home/templates/Home/calendar.html
{% load static %}
<html>
    <head>
        <title>Event Calendar</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'Home/css/styleCal.css' %}">
        <link rel="stylesheet" href="{% static 'Home/css/evo-calendar.min.css' %}">
        <link rel="stylesheet" href="{% static 'Home/css/evo-calendar.midnight-blue.min.css' %}">
    </head>
    <body>
        <div class="hero">
            <div id="calendar"></div>
        </div>
        <script src="https://cdn.jsdelivr.net/npm/jquery@3.4.1/dist/jquery.min.js"></script>
        <script src="{% static 'Home/js/evo-calendar.min.js' %}"></script>

        <script>
            $(document).ready(function() {
                $('#calendar').evoCalendar({
                    theme: "Midnight Blue",
                    calendarEvents: [{
                            id: 'event1', // Event's ID (required)
                            name: "New Year", // Event name (required)
                            date: "January/1/2021", // Event date (required)
                            description: "The heart touching greetings will make anyone feel special. Happy New Year!",                            
                            type: "holiday", // Event type (required)
                            everyYear: true // Same event every year (optional)
                    },
                    {
                            id: 'event2', // Event's ID (required)
                            name: "Women's Day", // Event name (required)
                            date: "March/8/2021", // Event date (required)
                            description: "Women's Day",
                            type: "holiday", // Event type (required)
                            everyYear: true // Same event every year (optional)
                    },
                    {
                            id: 'event3', // Event's ID (required)
                            name: "Makar Sankranti", // Event name (required)
                            date: "January/14/2021", // Event date (required)
                            description: "Happy Sankranti",                            
                            type: "holiday", // Event type (required)
                            everyYear: true // Same event every year (optional)
                    },
                    {
                            id: 'event4', // Event's ID (required)
                            name: "Republic Day", // Event name (required)
                            date: "January/26/2021", // Event date (required)
                            description: "Republic Day",                            
                            type: "holiday", // Event type (required)
                            everyYear: true // Same event every year (optional)
                    },
                    {
                            id: 'event5', // Event's ID (required)
                            name: "Republic Day", // Event name (required)
                            date: "January/26/2021", // Event date (required)
                            description: "Republic Day",                            
                            type: "holiday", // Event type (required)
                            everyYear: true // Same event every year (optional)
                    },
                    {
                            id: 'event6', // Event's ID (required)
                            name: "Holi", // Event name (required)
                            date: "March/29/2021", // Event date (required)
                            description: "Holi",                            
                            type: "holiday", // Event type (required)
                            everyYear: true // Same event every year (optional)
                    },
                    {
                            id: 'event7', // Event's ID (required)
                            name: "Good Friday", // Event name (required)
                            date: "April/2/2021", // Event date (required)
                            description: "Good Friday",                            
                            type: "holiday", // Event type (required)
                            everyYear: false // Same event every year (optional)
                    },
                    {
                            id: 'event8', // Event's ID (required)
                            name: "Easter", // Event name (required)
                            date: "April/4/2021", // Event date (required)
                            description: "Easter",                            
                            type: "holiday", // Event type (required)
                            everyYear: false // Same event every year (optional)
                    },
                    {
                            id: 'event9', // Event's ID (required)
                            name: "Ugadi/ Chaitra Sukladi/ Gudi Padava/ Cheti Chand", // Event name (required)
                            date: "April/13/2021", // Event date (required)
                            description: "Regional New year",                            
                            type: "holiday", // Event type (required)
                            everyYear: false // Same event every year (optional)
                    },
                    {
                            id: 'event10', // Event's ID (required)
                            name: "Vishu/ Vaisakhi/ Mesadi", // Event name (required)
                            date: "April/14/2021", // Event date (required)
                            description: "Regional New Year",                            
                            type: "holiday", // Event type (required)
                            everyYear: false // Same event every year (optional)
                    },
                    {
                            id: 'event11', // Event's ID (required)
                            name: "Ram Navami", // Event name (required)
                            date: "April/21/2021", // Event date (required)
                            description: "Ram Navami",                            
                            type: "holiday", // Event type (required)
                            everyYear: false // Same event every year (optional)
                    },
                    {
                            id: 'event12', // Event's ID (required)
                            name: "Eid-Ul-Fitr", // Event name (required)
                            date: "May/14/2021", // Event date (required)
                            description: "Eid",                            
                            type: "holiday", // Event type (required)
                            everyYear: false // Same event every year (optional)
                    },
                    {
                            id: 'event13', // Event's ID (required)
                            name: "Bakrid", // Event name (required)
                            date: "July/21/2021", // Event date (required)
                            description: "Bakrid",                            
                            type: "holiday", // Event type (required)
                            everyYear: false // Same event every year (optional)
                    },
                    {
                            id: 'event14', // Event's ID (required)
                            name: "Independence Day", // Event name (required)
                            date: "August/15/2021", // Event date (required)
                            description: "Independence Day",                            
                            type: "holiday", // Event type (required)
                            everyYear: true // Same event every year (optional)
                    },
                    {
                            id: 'event15', // Event's ID (required)
                            name: "Muharram", // Event name (required)
                            date: "August/19/2021", // Event date (required)
                            description: "Muharram",                            
                            type: "holiday", // Event type (required)
                            everyYear: false // Same event every year (optional)
                    },
                    {
                            id: 'event16', // Event's ID (required)
                            name: "Onam", // Event name (required)
                            date: "August/21/2021", // Event date (required)
                            description: "Onam",                            
                            type: "holiday", // Event type (required)
                            everyYear: false // Same event every year (optional)
                    },
                    {
                            id: 'event17', // Event's ID (required)
                            name: "Janmashtami", // Event name (required)
                            date: "August/30/2021", // Event date (required)
                            description: "Krishna Jayanthi",                            
                            type: "holiday", // Event type (required)
                            everyYear: false // Same event every year (optional)
                    },
                    {
                            id: 'event18', // Event's ID (required)
                            name: "Ganesh Chaturthi", // Event name (required)
                            date: "September/10/2021", // Event date (required)
                            description: "Ganesh Chaturthi",                            
                            type: "holiday", // Event type (required)
                            everyYear: false // Same event every year (optional)
                    },
                    {
                            id: 'event19', // Event's ID (required)
                            name: "Gandhi Jayanthi", // Event name (required)
                            date: "October/2/2021", // Event date (required)
                            description: "Gandhi Jayanthi",                            
                            type: "holiday", // Event type (required)
                            everyYear: true // Same event every year (optional)
                    },
                    {
                            id: 'event20', // Event's ID (required)
                            name: "Dussehra", // Event name (required)
                            date: "October/15/2021", // Event date (required)
                            description: "Dussehra",                            
                            type: "holiday", // Event type (required)
                            everyYear: false // Same event every year (optional)
                    },
                    {
                            id: 'event21', // Event's ID (required)
                            name: "Diwali", // Event name (required)
                            date: "November/3/2021", // Event date (required)
                            description: "Diwali",                            
                            type: "holiday", // Event type (required)
                            everyYear: false // Same event every year (optional)
                    },
                    {
                            id: 'event22', // Event's ID (required)
                            name: "Diwali", // Event name (required)
                            date: "November/4/2021", // Event date (required)
                            description: "Diwali",                            
                            type: "holiday", // Event type (required)
                            everyYear: false // Same event every year (optional)
                    },
                    {
                            id: 'event23', // Event's ID (required)
                            name: "Christmas", // Event name (required)
                            date: "December/25/2021", // Event date (required)
                            description: "Christmas",                            
                            type: "holiday", // Event type (required)
                            everyYear: true // Same event every year (optional)
                    }
                ]
                })
            })
        </script>

    </body>

</html>

Home/templates/Home/contact.html
{% load static%}
<!DOCTYPE html>
<html>
    <head>
        <meta name = "viewport" content = "width=device-width,initial-scale=1.0">
        <title>Contact Us</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'Home/css/styleContact.css' %}">
    </head>
    <body>

        <header>
            <a id="logo" href="{% url 'Home:home'%}">
                <img src="{%  static 'Home/images/amrita.jpg' %}" alt="Logo">
                <span>Smart Attendance Management System</span>
            </a>

            <!-- Main Navigation Links-->
            <nav>
                <ul>
                    <li><a href="{% url 'Home:home' %}">Home</a></li>
                    <li><a href="{% url 'Home:about' %}">About</a></li>
                    <li><a href="{% url 'Home:contact' %}">Contact Us</a></li>
                    <li><a href="{% url 'Home:calendar' %}">Calendar</a></li>
                    <li><a href="{% url 'login'%}">Login</a></li>
                </ul>
            </nav>

        </header>
        <section class="contact">
            <div class="content">
                <h2>Contact Us</h2>
                <p>We are happy to help</p>
            </div>

            <div class="container">
                <div class="contactInfo">
                    <div class="box">
                        <div class="icon"><i class="fa fa-map-marker" aria-hidden="true"></i></div>
                        <div class="text">
                            <h3>Address</h3>
                            <p>Amrita Vishwa Vidyapeetham, <br>Ettimadai</p>
                        </div>
                    </div>

                    <div class="box">
                        <div class="icon"><i class="fa fa-phone" aria-hidden="true"></i></div>
                        <div class="text">
                            <h3>Phone</h3>
                            <p>99999900000</p>
                        </div>
                    </div>

                    <div class="box">
                        <div class="icon"><i class="fa fa-envelope-o" aria-hidden="true"></i></div>
                        <div class="text">
                            <h3>Email</h3>
                            <p>queries.team6.attendance@gmail.com</p>
                        </div>
                    </div>
                </div>
                <div class="contactForm">
                    <form
                    action="https://formspree.io/f/mrgrgjgn"
                    method="POST">
                        <h2>Send Message</h2>
                        <div class = "inputBox">
                            <input type="text" name="Name" required="required">
                            <span>Full Name</span>
                        </div>

                        <div class = "inputBox">
                            <input type="text" name="_replyto" required="required">
                            <span>Email</span>
                        </div>

                        <div class = "inputBox">
                            <textarea required="required" name="Message"></textarea>
                            <span>Type your Message . . .</span>
                        </div>

                        <div class = "inputBox">
                            <input type ="submit" name="SubmitButton" value="Send">
                            <a href="{% url 'Home:home'%}" class="btn"> Back </a>
                        </div>
                    </form>
                </div>
            </div>
        </section>
    </body>
</html>

Home/templates/Home/mainhomepage.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>Smart Attendance Management System</title>
        <!-- attach our stylesheet -->
        <link rel="stylesheet" href="{% static 'Home/css/style.css' %}">
    </head>

    <body>
        <!-- the header images/amrita.jpg -->
        <header>
            <a id="logo" href="{% url 'Home:home' %}">
                <img src="{% static 'Home/images/amrita.jpg' %}" alt="Logo">
                <span>Smart Attendance Management System</span>
            </a>

            <!-- Main Navigation Links-->
            <nav>
                <ul>
                    <li><a href="{% url 'Home:home'%}">Home</a></li>
                    <li><a href="{% url 'Home:about' %}">About</a></li>
                    <li><a href="{% url 'Home:contact' %}">Contact Us</a></li>
                    <li><a href="{% url 'Home:calendar' %}">Calendar</a></li>
                    <li><a href="{% url 'login'%}">Login</a></li>
                </ul>
            </nav>

        </header>

        <!-- The Main Content -->
        <main>
            <!--Hero Content -->
            <div class="hero">
                <!-- Content for the hero -->
                <div class="hero-content">
                    <h1 class ="hero-title">Smart Attendance Management</h1>
                    <p>This application is used to store and manage the attendance of the Students</p>

                    <a href="{% url 'Home:about' %}">Know More</a>
                    <a href="{% url 'Home:contact' %}">Call Us</a>
                </div>
            </div>

            <!-- Features Section -->
            <div class ="site-section">
                <div class="site-section-inside">
                    <div class="section-header">
                        <h2>Key Features</h2>
                    </div>

                    <div class="feature-box">
                        <img src="{% static 'Home/images/like.png' %}" alt="Easy to use">
                        <h5>Easy to Use</h5>
                        <p>Very easy to navigate and use</p>
                    </div>

                    <div class="feature-box">
                        <img src="{% static 'Home/images/faces.png' %}" alt="Face to Use">
                        <h5>Face Recognition</h5>
                        <p>Saves a lot of time</p>
                    </div>

                    <div class="feature-box">
                        <img src="{% static 'Home/images/heart.png' %}" alt="Face to Use">
                        <h5>You'll Love It</h5>
                        <p>An app that you would love</p>

                    </div>
                </div>

                <!--Creators Section-->
                <div class="site-section site-section-secondary">
                    <div class="site-section-inside">
                        <div class="section-header">
                            <h2>Creators</h2>
                        </div>

                        <div class="testimonial-box">
                            <div class="testimonial-content">
                                Developer 1
                            </div>
                            <div class="testimonial-author">
                                <img src="{% static 'Home/images/Akhila.jpg' %}" alt="Akhila Kolli">
                                <h5>Akhila Kolli</h5>
                                <span>Front End and Back End</span>
                            </div>
                        </div>

                        <div class="testimonial-box">
                            <div class="testimonial-content">
                                Developer 2
                            </div>
                            <div class="testimonial-author">
                                <img src="{% static 'Home/images/Sanjith.jpg' %}" alt="Sanjith">
                                <h5>Sanjith</h5>
                                <span>Scrum Master</span>
                            </div>
                        </div>

                        <div class="testimonial-box">
                            <div class="testimonial-content">
                                Developer 3
                            </div>
                            <div class="testimonial-author">
                                <img src="{% static 'Home/images/Hari.jpg' %}" alt="Hari">
                                <h5>Hari</h5>
                                <span>Facial Recognition model</span>
                            </div>
                        </div>

                        <div class="testimonial-box">
                            <div class="testimonial-content">
                                Developer 4
                            </div>
                            <div class="testimonial-author">
                                <img src="{% static 'Home/images/Hitharth.jpg' %}"" alt="Hitharth">
                                <h5>Hitharth Kadam</h5>
                                <span>Tester</span>
                            </div>
                        </div>

                        <div class="testimonial-box">
                            <div class="testimonial-content">
                                Developer 5
                            </div>
                            <div class="testimonial-author">
                                <img src="{% static 'Home/images/Shyam.jpg' %}" alt="Shyam">
                                <h5>Shyam Nagarajan</h5>
                                <span>Dashboard design</span>
                            </div>
                        </div>

                        <div class="testimonial-box">
                            <div class="testimonial-content">
                                Developer 6
                            </div>
                            <div class="testimonial-author">
                                <img src="{% static 'Home/images/Priyatham.jpg' %}" alt="Priyatham">
                                <h5>Priyatham</h5>
                                <span>Tester</span>
                            </div>
                        </div>
                        
                    </div>
                </div>


            </div>

        </main>
        <!-- the footer -->
        <footer>
            <span>SAMS Web App<br>Copyright &copy; Team6 </span>
        </footer>
    </body>
</html>